analytics.account={"id"\:200326,"name"\:"mohit.katalon","uuid"\:"651e16c4-cef5-4162-9c43-ace71f53be52","domain"\:"mohit-kumar-katalon"}
analytics.integration.enable=true
analytics.onpremise.enable=true
analytics.onpremise.organization=null
analytics.onpremise.server=https\://testops.katalon.io
analytics.project={"id"\:3346204,"name"\:"TrueTest","teamId"\:3318257,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:200326,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3318257,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.hub.switchHub.enable=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
onpremise.email=mohit.kumar@katalon.com
onpremise.password=H0Q291REJi8mZmD6Fe3ZMw\=\=
